Name:           ros-jade-vrpn
Version:        0.7.33
Release:        6%{?dist}
Summary:        ROS vrpn package

Group:          Development/Libraries
License:        BSL1.0
URL:            https://github.com/vrpn/vrpn/wiki
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-catkin
BuildRequires:  cmake

%description
The VRPN is a library and set of servers that interfaces with virtual-reality
systems, such as VICON, OptiTrack, and others.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Jun 22 2015 Paul Bovbel <pbovbel@clearpathrobotics.com> - 0.7.33-6
- Autogenerated by Bloom

* Fri Jun 19 2015 Paul Bovbel <pbovbel@clearpathrobotics.com> - 0.7.33-5
- Autogenerated by Bloom

* Fri Jun 19 2015 Paul Bovbel <pbovbel@clearpathrobotics.com> - 0.7.33-4
- Autogenerated by Bloom

* Fri Jun 19 2015 Paul Bovbel <pbovbel@clearpathrobotics.com> - 0.7.33-3
- Autogenerated by Bloom

* Fri Jun 19 2015 Paul Bovbel <pbovbel@clearpathrobotics.com> - 0.7.33-2
- Autogenerated by Bloom

